// app/layout.tsx or app/layout.jsx

import { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import { SidebarProvider } from "@/components/ui/sidebar"

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] })
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body className="antialiased bg-background text-foreground">
        <SidebarProvider>
          <main className="flex min-h-screen">
            {/* Sidebar would be placed here */}
            {/* <Sidebar>...</Sidebar> */}
            <div className="flex-1">{children}</div>
          </main>
        </SidebarProvider>
      </body>
    </html>
  )
}
